INSERT INTO USERDATA(EMAIL,PASSWORD,FNAME,LNAME,USERTYPE)
VALUES('admin@admin.com', 'mypassword', 'System', 'Administrator','ADMIN');

INSERT INTO USERDATA(EMAIL,PASSWORD,FNAME,LNAME,USERTYPE)
VALUES('user1@user.com', 'mypassword', 'Donald', 'User','GENUSER');

INSERT INTO USERDATA(EMAIL,PASSWORD,FNAME,LNAME,USERTYPE)
VALUES('user2@user.com', 'mypassword', 'Melania', 'User','GENUSER');

INSERT INTO USERDATA(EMAIL,PASSWORD,FNAME,LNAME,USERTYPE)
VALUES('user3@user.com', 'mypassword', 'Ivanka', 'User','GENUSER');

INSERT INTO USERDATA(EMAIL,PASSWORD,FNAME,LNAME,USERTYPE)
VALUES('user4@user.com', 'mypassword', 'Jared', 'User','GENUSER');

INSERT INTO USERDATA(EMAIL,PASSWORD,FNAME,LNAME,USERTYPE)
VALUES('user5@user.com', 'mypassword', 'Mary', 'User','GENUSER');

INSERT INTO PRODUCTS(NAME,DESCRIPTION,PRICE,IMAGE_LOCATION,QUANTITY,TYPE)
VALUES('Philips','Universal Philips remote',15,'philips.jpg','2','Infrared');

INSERT INTO PRODUCTS(NAME,DESCRIPTION,PRICE,IMAGE_LOCATION,QUANTITY,TYPE)
VALUES('JVC','Universal JVC remote',10,'oneforall.jpg','2','Infrared');

INSERT INTO PRODUCTS(NAME,DESCRIPTION,PRICE,IMAGE_LOCATION,QUANTITY, TYPE)
VALUES('Sky Voice','Voice Control',45,'skyvoice.jpg','2','Voice');

INSERT INTO PRODUCTS(NAME,DESCRIPTION,PRICE,IMAGE_LOCATION,QUANTITY,TYPE)
VALUES('Google Voice','For all android smart TVs',30,'googlevoice.jpg','2','Voice');

INSERT INTO PRODUCTS(NAME,DESCRIPTION,PRICE,IMAGE_LOCATION,QUANTITY,TYPE)
VALUES('Flysky Drone Control','Universal Drone Remote',80,'flysky.jpg','2','Radio');

INSERT INTO PRODUCTS(NAME,DESCRIPTION,PRICE,IMAGE_LOCATION,QUANTITY,TYPE)
VALUES('Explorer','Advanced Drone Remote',150,'advanceddrone.jpg','2','Radio');


INSERT INTO CATEGORIES(TYPE)
VALUES('Infrared');

INSERT INTO CATEGORIES(TYPE)
VALUES('Voice');

INSERT INTO CATEGORIES(TYPE)
VALUES('Voice');

INSERT INTO PAYMENTS(USER_ID,TOTAL)
VALUES(1, 560);

INSERT INTO PAYMENTS(USER_ID,TOTAL)
VALUES(2,45);

INSERT INTO PAYMENTS(USER_ID,TOTAL)
VALUES(3, 55);










